# ---------------------------------------------------------------------------
#                    Spacemacs environment variables
# ---------------------------------------------------------------------------
# This file has been generated by Spacemacs. It contains all environment
# variables defined in your default shell except those with names matching
# regexps in `spacemacs-ignored-environment-variables'. If you add any
# duplicate settings for a variable, only the first setting is effective.
# PATH is a special case: all PATH settings are read, each non-duplicate
# directory entry is appended to the `exec-path' variable, and then PATH is
# set to the final value of `exec-path'.
#
# You can safely edit this file to change values or add or remove entries.
# Spacemacs won't overwrite the file unless you call the function
# `spacemacs/force-init-spacemacs-env'.
#
# If you don't want to use this file but would rather manage your environment
# variables yourself, remove the call to `spacemacs/load-spacemacs-env' from
# the `dotspacemacs/user-env' function in your dotfile and replace it with
# your own initialization code. You can use `exec-path-from-shell' if you add
# it to your additional packages, or simply use `setenv' and
# `(add-to-list 'exec-path ...)', which are built-in.
#
# It is recommended to use this file as it unambiguously and explicitly sets
# the values of your environment variables.
# ---------------------------------------------------------------------------

# Environment variables:
# ----------------------
DISPLAY=:10.0
HOME=/home/wrydz
LANG=C.UTF-8
LESSCLOSE=/bin/lesspipe %s %s
LESSOPEN=| /bin/lesspipe %s
LOGNAME=wrydz
LS_COLORS=
PATH=/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
PWD=/home/wrydz
QT_ACCESSIBILITY=1
SESSION_MANAGER=local/DESKTOP-0J65QS1:@/tmp/.ICE-unix/679,unix/DESKTOP-0J65QS1:/tmp/.ICE-unix/679
SHELL=/bin/bash
SHLVL=2
UID=1000
USER=wrydz
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
XRDP_SESSION=1
XRDP_SOCKET_PATH=/var/run/xrdp/sockdir
_=/usr/bin/env
